.\" Copyright (c) 2016 Tresys Technology, LLC.  All rights reserved.
.TH apol 1 2016-02-20 "SELinux Project" "SETools: утилиты анализа политики SELinux"

.SH ИМЯ
apol \- графическая утилита анализа политики SELinux

.SH ОБЗОР
\fBapol\fR [OPTIONS] [POLICY]

.SH ОПИСАНИЕ
.PP
\fBapol\fR - графическая утилита, которая позволяет пользователю изучить и проанализировать аспекты политики SELinux.

.SH ПОЛИТИКА
.PP
\fBapol\fR поддерживает загрузку политик SELinux в одном из двух форматов.
.RS
.IP "source:"
Один текстовый файл, содержащий источник монолитной политики. Этот файл обычно называется policy.conf.
.IP "binary:"
Один файл, содержащий двоичную политику. В системах Linux название этого файла обычно соответствует версии, например, \fIpolicy.30\fR. В системах Android этот файл обычно называется \fIsepolicy\fR.
.RE
.PP
Если файл политики не указан, она не будет загружена при запуске \fBapol\fR.

.SH ПАРАМЕТРЫ
.IP "-h, --help"
Вывести справочные сведения и выйти.
.IP "--version"
Вывести сведения о версии и выйти.
.IP "-v, --verbose"
Вывести дополнительные информационные сообщения.
.IP "--debug"
Включить отладочный вывод.

.SH ОШИБКИ
Пожалуйста, сообщайте об ошибках через систему отслеживания ошибок SETools, https://github.com/SELinuxProject/setools/issues

.SH СМОТРИТЕ ТАКЖЕ
sediff(1), sedta(1), seinfo(1), seinfoflow(1), sesearch(1)

.SH АВТОРЫ
Chris PeBenito <pebenito@ieee.org>. Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
